spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}/${DB_DATABASE:questionnaire}?characterEncoding=utf8&useSSL=false&useUnicode=true
    username: ${DB_USER:dbuser}
    password: ${DB_PASSWORD:dbpasswd}
    driverClassName: com.mysql.jdbc.Driver
